content/broadcasts/230519-amsterdam/index.en.yaml
content/broadcasts/230519-amsterdam/index.fr.yaml

Fixes None
Fix data ai world presenters.

fix(content): update conf presenters

---

content/pages/1.discover/1.history/index.en.md
content/pages/1.discover/1.history/index.fr.md

As discussed in last meeting, I propose to remove history for now to not postpone the official website launch. Page may come back once someone wishes to write a page about it which could also be named contributors

feat(pages): history page removal

---

content/pages/1.discover/1.usages/index.en.md
content/pages/1.discover/1.usages/index.fr.md
yarn.lock

Usage page was mention in last meeting.
Translation will take place after validation

feat(pages): usage page

---

.github/workflows/pull-request.yml

Add an action on each PR to check if a build pass.

ci: test build for each pr

---

next.config.js

Update next config file to allow website build with github actions.

Update next export for github pages build

---

package.json
yarn.lock

Upgrade Next.js to fix `.txt` pb.

chore(project): upgrade next

---

content/pages/1.discover/2.features/index.fr.md

This is a proposal initially written in French.

feat(pages): feature page

---

content/pages/3.contribute/2.build/1.build-release.md
content/pages/3.contribute/2.build/2.versioning.md

Original URL is https://github.com/TOSIT-IO/TDP/blob/main/VERSIONING.md

feat(pages): versioning import

---

content/pages/1.discover/3.security/index.fr.md
content/pages/1.discover/4.roadmap/index.fr.md
content/pages/1.discover/index.fr.md
package-lock.json
package.json

This PR introduce page slug translation. For example: `http://localhost:3000/fr/discover` is now `http://localhost:3000/fr/decouvrir`. This will break previously created French pages.

fix(pages)!: i18n slugs (breaking change)

---

content/pages/1.discover/4.roadmap/index.en.md

Present the project roadmap with current and future actions lead by the community.

docs(pages): roadmap

---

content/reports/231117-contributors.md

Report for the 17 nov. contributors meeting.

feat(reports): 231117 contributors meeting

---

README.md

Following [this discussion](https://github.com/orgs/TOSIT-IO/discussions/92)

docs(project): fix title

---

content/reports/240209-contributors.md

Report for the 09 February contributors' meeting.

feat(reports): 230209 contributors meeting

---

content/reports/230202-contributors.md

Report for the 02 feb. contributors meeting.

feat(reports): 230202 contributors meeting

---

content/reports/240216-contributors.md

Report of the 16th February contributors' meeting.

feat(reports): 230216 contributors meeting

---

content/reports/240223-contributors.md

Report of the 23rd February contributors' meeting.

feat(reports): 240223 contributors report

---

content/reports/240308-contributors.md

March 8th 2024 contributor's report

feat: contributors report 08032024

---

content/reports/240315-contributors.md

March 15th contributors' report

feat(reports): 240315 contributors report

---

content/reports/240322-contributors.md

Contributors' report 22nd of march 2024

feat(reports): contributors' report 22nd of march 2024

---

next.config.js

Hi @rpignolet, we agreed to preserve main branch access to non-content and dev related commits.

refactor(project): remove trailing space to next config

---

content/reports/240503-contributors.md

3rd of May contributors' report.

feat(reports): 240503 contributors report

---

content/reports/240517-contributors.md

17th of May contributors' report

feat(reports): 240517 contributors report

---

src/app/[lang]/(home)/page.js
src/layout/home/Logos.js

fix(layout): home logo invisible on safari

---

src/app/[lang]/(home)/page.js

... as well as lighter paragraph font weight in the features texts.

fix(layout): home features icons not visible

---

content/reports/240524-contributors.md

24th of May contributors' report.

feat(reports): 240524 contributors report

---

content/reports/240607-contributors.md

7th of June contributors' report.

feat(reports): 240607 contributors report

---

tailwind.config.js
typography.js

Minor refactoring, no code change

refactor(project): tailwind and typography eslint validation

---

package-lock.json
package.json

Latest Redac version 0.3.2 is creating an issue with the security mdx page

fix(project): redac version freeze 0.3.1

---

package-lock.json
package.json
src/app/[lang]/(pages)/[...slug]/page.js
src/app/[lang]/(reports)/contribute/develop/reports/[...slug]/page.js

Minor renaming after upgrading the redac dependency.

refactor(project): latest redac

---

content/reports/240705-contributors.md

Contributors' report of 5th of July 2024.

feat(reports): 050724 contributors report

---

content/reports/240712-contributors.md

Contributors' report of the 12th of July 2024.

feat(reports): 120724 contributors report

---

content/reports/240719-contributors.md

19th of July 2024 contributors' report.

feat(reports): contributors' report 240719

---

content/reports/240802-contributors.md

Contributor's report of the 2nd of August 2024.

feat(reports): contributors' report 240802

---

content/reports/240809-contributors.md

Contributors' report of 9th of August 2024.

feat(reports): contributors' report 240809

---

content/reports/240906-contributors.md

Contributor's report of the 6th of September 2024.

feat(reports): contributors' report 240906

---

content/reports/240920-contributors.md

Contributors' report of 20th of September 2024.

feat(reports): contributors' report 240920

---

content/reports/240927-contributors.md

Contributors' report of 27th of September 2024.

feat(reports): 240927 contributors' report

---

content/reports/241004-contributors.md

Contributors' report of 4th of October 2024.

feat(reports): contributors' report 241004

---

content/reports/241011-contributors.md

Contributors ' report of 11th of October 2024.

feat(reports): contributors' report 241011

---

content/reports/241018-contributors.md

Hello, 
This is the report of the 18th October 2024 meeting. 
Please, could you approve and merge this pull request ?
Regards, 
Alexis.

feat(reports): report for the 18th October 2024

---

content/reports/241108-contributors.md

Contributors' report of 8th of November.

feat(reports): report for the 8th November 2024

---

content/reports/241115-contributors.md

Contributors' report of November 15th.

feat(reports): report for the 15th November 2024

---

content/reports/241129-contributors.md

Contributors' report of the 29th of November.

feat(reports): report of the 29th of November 2024

---

content/reports/241206-contributors.md

Contributors' report of 6th of December 2024.

feat(reports): contributors' report of 6th of December 2024

---

content/reports/241213-contributors.md

Contributors' report of the 13th of December.

feat(reports): report of the 13th of December 2024

---

content/reports/241220-contributors.md

Contributors' report of the 20th of December 2024.

feat(reports): contributors report of 20th of December 2024

---

content/reports/250110-contributors.md

Contributors' report of 10th of January 2025

feat(reports): contributors report of 10th of January 2025

---

content/pages/3.contribute/2.build/2.versioning.md

feat: update versioning to new behaviour of TDP second digit

---

content/reports/250124-contributors.md

Contributors' report of 24th of January 2025.

feat(reports): contributors report 24th of january 2025

---

content/reports/250131-contributors.md

Contributors report of 31st of January 2025.

feat(reports): contributors report 31st of january 2025

---

content/reports/250207-contributors.md

Contributors report of 7th of February 2025.

feat(reports): contributors report of 7th of february

---

content/pages/1.discover/05.stacks/3.tdp2-0.en.md
src/mdx/components/stacks/data.ts

Added tdp-core components for stack 2.0 as well as tdp-extra and tdp-observability components.

feat(pages): created tables for stack 2.0
